export const ROLES = {
  STUDENT: 'student',
  TEACHER: 'teacher',
  MENTOR: 'mentor',
  RECRUITER: 'recruiter',
  ADMIN: 'admin',
  SUPER_ADMIN: 'superadmin',
} as const;

export type Role = (typeof ROLES)[keyof typeof ROLES];

export const ROLE_PERMISSIONS: Record<string, string[]> = {
  student: [
    'read:courses',
    'enroll:courses',
    'read:jobs',
    'apply:jobs',
    'read:mentors',
    'book:mentor_sessions',
    'use:ai_features',
    'read:forum',
    'write:forum',
    'manage:own_profile',
    'download:certificates',
    'build:resume',
    'take:quizzes',
    'attend:live_classes',
  ],
  teacher: [
    'read:courses',
    'create:courses',
    'update:own_courses',
    'delete:own_courses',
    'read:own_students',
    'create:quizzes',
    'issue:certificates',
    'host:live_classes',
    'read:own_earnings',
    'read:forum',
    'write:forum',
    'manage:own_profile',
  ],
  mentor: [
    'read:courses',
    'manage:mentor_profile',
    'manage:mentor_sessions',
    'read:mentee_profiles',
    'read:forum',
    'write:forum',
  ],
  recruiter: [
    'create:jobs',
    'update:own_jobs',
    'delete:own_jobs',
    'read:student_profiles',
    'manage:applications',
    'schedule:interviews',
    'manage:company_profile',
  ],
  admin: [
    'manage:users',
    'approve:courses',
    'manage:payments',
    'manage:certificates',
    'read:analytics',
    'manage:notifications',
    'manage:cms',
    'manage:support_tickets',
    'read:ai_usage',
  ],
  superadmin: ['*'],
};
